### ISSUE TITLE
win32api error

### ISSUE THREAD

**Issue by atrimn** [SirFroweey/FindADownload#1]
Im getting error No module win32api when i try to search for stuff

**Comment by SirFroweey** [comment]
Per Scrapy's document, apparently its a known bug, to resolve it install pywin32: [https://sourceforge.net/projects/pywin32/files/pywin32/Build%20221/pywin32-221.win32-py2.7.exe/download](https://sourceforge.net/projects/pywin32/files/pywin32/Build%20221/pywin32-221.win32-py2.7.exe/download)

**Comment by SirFroweey** [comment]
No longer relevant since project has been refactored to mechanize/lxml solution.
